### ISSUE TITLE
Bug in detect_dm_csv when sample=TRUE

### ISSUE THREAD

**Issue by spinwards** [djvanderlaan/LaF#10]
detect_dm_csv fails with the error: 

`Error in sample_lines(filename, n = nrow, nlines = nlines) : 
  n should be a number`

The problem is that the code attempts to pass the nrows parameter in to sample_lines, but the parameter name is spelled as "nrow" instead of "nrows".

<pre>detect_dm_csv <- function(filename, sep=",", dec=".", header=FALSE, 
        <b><i>nrows</i></b>=1000, nlines=NULL, sample=FALSE, factor_fraction=0.4, ...) {
    if (sample) {
        lines <- sample_lines(filename, n=<b><i>nrow</i></b>, nlines=nlines)
        con <- textConnection(lines)
    } else con <- file(filename, "rt")
</pre>

To confirm that this is the problem, I copied the function definition into my environment and updated the call to sample_lines. The change took care of the problem. 

Here is the updated function:

```R
detect_dm_csv<-function (filename, sep = ",", dec = ".", header = FALSE, nrows = 1000, 
                         nlines = NULL, sample = FALSE, factor_fraction = 0.4, ...) 
{
  if (sample) {
    lines <- sample_lines(filename, n = nrows, nlines = nlines)
    con <- textConnection(lines)
  }
  else con <- file(filename, "rt")
  data <- read.table(con, nrows = nrows, sep = sep, dec = dec, 
                     header = header, ...)
  close(con)
  name <- names(data)
  type <- sapply(data, function(d) {
    type <- class(d)
    if (identical(type, "factor")) {
      f <- nlevels(d)/length(d)
      if (f > factor_fraction) {
        type <- "string"
      }
      else {
        type <- "categorical"
      }
    }
    else if (identical(type, "numeric")) {
      type <- "double"
    }
    else if (identical(type, "character")) {
      type <- "string"
    }
    else if (identical(type, "integer")) {
    }
    else {
      warning("Unsupported type '", type, "'; using default type 'string'")
      type <- "string"
    }
    return(type)
  })
  return(list(type = "csv", filename = filename, columns = data.frame(name = name, 
                                                                      type = type, stringsAsFactors = FALSE), dec = dec, sep = sep, 
              skip = ifelse(header, 1, 0)))
}
```

**Comment by djvanderlaan** [comment]
@spinwards Thanks for reporting! Should be fixed now.
