### ISSUE TITLE
[feature request] Progress bar for `process_blocks`?

### ISSUE THREAD

**Issue by talegari** [djvanderlaan/LaF#11]
> Progress bar for `process_blocks`

- This would make longish waiting times for friendly!
- Is this feasible?
- Since, we know the number of number of rows of the `laf` object(dataframe) and `nrows`, we can guess the number of blocks to be processed. A dot or a dash may be printed periodically (so that there are say 100 dots in total)

**Comment by djvanderlaan** [comment]
Hi @talegari,

Yes, that is feasible. The number of rows is not always available: when you open a file and process it using `process_block` it is in principle not available. For fixed width files, it is cheap to determine the number of lines, but for CSV files, the complete file needs to be scanned which can take quite some time. However, as long as the progress bar is not on by default and warning the user for the possible extra calculation time in the documentation, this should be ok. 

So, I will add this. I am not sure I have time to work on this his week.
