### ISSUE TITLE
Error in .laf_to_typecode(column_types) : object 'categorical' not found

### ISSUE THREAD

**Issue by couchmarauder** [djvanderlaan/LaF#18]
Hello,
I keep encountering the error code above when i run this code using LaF on a fixed width ascii file, what am I doing wrong? 

dat <-laf_open_fwf (filename= “myfile.txt”,  column_widths= c (12, 3, 6, 75, 5, 9, 1, 1, 1, 10, 4, 1, 1, 1, 1, 3, 1, 4, 1, 1, 1, 1, 15, 1, 1, 9, 1, 6, 1, 9, 1, 5, 1, 5, 5, 1, 4, 4, 1, 1), column_types =-c(string’,’integer’,’integer’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’,’string’), column_names =c(‘ServiceCenterCyclePageLine’,’Rownumber’,’Facilitylinenumber’,’Facilityname’,’Zipcode’,’Facilitytype’,’Licensedyear’,’Acquiredyear’,’ConductCHNA’,’ContentsCHNA’,’YearCHNA’,’CHNAcommunityinput’,’CHNAwOtherfacilities’,’CHNAwNonhospfacilities’,’Needsassessmentpublic’,’Howpubliclyavailable’,’Impstrategyadopted’,’Yearadopted’,’Impstrategywebsite’,’Impstrategyonreturn’,’Incur4959excisetax’,’File4720forexcisetax’,’Amountexcisetax’,’Explaineligibilityforassistance’,’Explainbasisforcharges’,’Factorsincalculatecharges’,’Explainassistanceapplication’,’Howexplained’,’Measurestopublicizeassistance’,’Howassistancewaspublicized’,’Writtennonpaymentpolicy’,’Nonpaymentpolicyactions’,’Collections’,’Collectionstype’,’Effortsbeforecollections’,’NondiscriminatoryERpolicy’,’ExplanationforERpolicy’,’Howmaximumchargesdetermined’,’Hospitalchargegtbilled’,’Chargeequalsgrosscharge’))

**Comment by djvanderlaan** [comment]
Hi @couchmarauder,

I can't reproduce your error. Could you try to generate a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)?

The code below is what I used to test your example. This doesn't give an error for me. I had to remove a - after `column_type = ` to get your example to run. 

```{r}

library(LaF)

column_widths <- c (12, 3, 6, 75, 5, 9, 1, 1, 1, 10, 4, 1, 1, 1, 1, 3, 1, 4, 1, 
    1, 1, 1, 15, 1, 1, 9, 1, 6, 1, 9, 1, 5, 1, 5, 5, 1, 4, 4, 1, 1)


nchar  <- sum(column_widths)
nlines <- 100
lines  <- sample(9, nchar * nlines, replace = TRUE)
lines  <- apply(array(lines, dim = c(nlines, nchar)), 1, paste0, collapse = "")
writeLines(lines, "myfile.txt")

dat <-laf_open_fwf(filename= "myfile.txt", 
  column_widths= column_widths,
  column_types = c("string","integer","integer","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string"), 
  column_names =c("ServiceCenterCyclePageLine","Rownumber","Facilitylinenumber",
    "Facilityname","Zipcode","Facilitytype","Licensedyear","Acquiredyear",
    "ConductCHNA","ContentsCHNA","YearCHNA","CHNAcommunityinput",
    "CHNAwOtherfacilities","CHNAwNonhospfacilities","Needsassessmentpublic",
    "Howpubliclyavailable","Impstrategyadopted","Yearadopted",
    "Impstrategywebsite","Impstrategyonreturn","Incur4959excisetax",
    "File4720forexcisetax","Amountexcisetax","Explaineligibilityforassistance",
    "Explainbasisforcharges","Factorsincalculatecharges",
    "Explainassistanceapplication","Howexplained",
    "Measurestopublicizeassistance","Howassistancewaspublicized",
    "Writtennonpaymentpolicy","Nonpaymentpolicyactions","Collections",
    "Collectionstype","Effortsbeforecollections","NondiscriminatoryERpolicy",
    "ExplanationforERpolicy","Howmaximumchargesdetermined",
    "Hospitalchargegtbilled","Chargeequalsgrosscharge"))

dat[,]

```
