### ISSUE TITLE
Quoted comma in first line (only) prevents reading any data

### ISSUE THREAD

**Issue by andrewdeines** [djvanderlaan/LaF#21]
A comma in a string field in the first line of data returns a data.frame with no rows.
Slightly modifying from the example in laf_open_csv() help file:
```
# Create temporary filename
tmpcsv  <- tempfile(fileext="csv")

# Generate test data
ntest <- 10
column_types <- c("integer", "integer", "double", "string")
testdata <- data.frame(
    a = 1:ntest,
    b = sample(1:2, ntest, replace=TRUE),
    c = round(runif(ntest), 13),
    d = c("ABC,DEF",  
          sample(c("jan",
                 "pier", 
                 "tjores", 
                 "corneel"), ntest-1, replace=TRUE))
    )

# Write test data to csv file
write.table(testdata, file=tmpcsv, row.names=FALSE, col.names=FALSE, sep=',')

# Create LaF-object
laf <- LaF::laf_open_csv(tmpcsv, column_types=column_types)
testdata
laf[,]
```

However, the same entry can be placed at other places in the file without issue.

```
testdata2 <- data.frame(
    a = 1:ntest,
    b = sample(1:2, ntest, replace=TRUE),
    c = round(runif(ntest), 13),
    d = sample(c("jan",
                 "pier", 
                 "tjores", 
                 "corneel"), ntest, replace=TRUE)
    )
testdata2[2,4]<-"ABC,DEF"

# Write test data to csv file
write.table(testdata2, file=tmpcsv, row.names=FALSE, col.names=FALSE, sep=',')

# Create LaF-object
laf2 <- LaF::laf_open_csv(tmpcsv, column_types=column_types)
testdata2
laf2[,]
```

In my use case, I have no control over the file contents.  Suggestions for workarounds are welcome.

**Comment by MaciekChudek** [comment]
I'm not sure if this project is still being developed, but a) I've just hit this bug myself and b) I think I've found the cause.

In `srv/csvreader.cpp` the function `CSVReader::next_line() ` (lines 79-137) has a bunch of logic for dealing with quote marks and only processes the separator of `open_quote` is false (line 114).  However the function `CSVReader::determine_ncolumns` (lines183-204) lacks this logic and counts every separator, even those inside the quotes.

Fixing this should just require copying the quote logic from `next_line` over to `determine_ncolumns`.

**Comment by pdbailey0** [comment]
@djvanderlaan can you accept this pull?

**Comment by djvanderlaan** [comment]
The package is maintained although a bit irregularly. Sorry for the long delay in fixing this. 

Thanks @MaciekChudek for the fix.
