### ISSUE TITLE
error message: Line ended while open quote 

### ISSUE THREAD

**Issue by elgabbas** [djvanderlaan/LaF#5]
Hello Jan,

I am having a problem while loading a big text data file (few gigabytes .txt file of some million records) into chunks using the LaF package. I am using a command like this to create a LaF object that links to my file:

> MyFileLaF <- laf_open_csv(filename = MyFile, column_types = rep("string", 254), sep = "\t", skip=0, column_names = paste0("V",1:254), trim=TRUE)

then, within a for loop, I am trying to extract some parts of the data (by subsetting certain columns of the file and dividing it into chunks of, let's say, 100,000 lines to run at once) using some code like:

> read_lines(x = MyFileLaF, rows = RowsToGet, columns = ColNumbers)

This works smoothly for some lines, but for others, it gives me this error message for no particular reason:

> Error: Line ended while open quote

I am not sure what is the reason of this error and at which line this occurs? Could you please let me know what is the reason of this error and how to fix it or at least ignore the problematic lines and keep working on the file (and if possible, to mark the lines numbers that have problems)?

Also, I've tried to use foreach() function along with the LaF package to best use of our multi-core server, but this always fails. Running the code itself outside the foreach loop works fine, but within the foreach() loop it always retains an empty data.frame object with 0 rows. Any thoughts?

Thanks in advance,
Ahmed

**Comment by elgabbas** [comment]
I've skimmed throughout the file and found that one of the problematic lines contains a double quotation " after one of the tabs without closing it.
Is there a way to ignore/replace such thing to bypass this error?

Thanks,
Ahmed

**Comment by djvanderlaan** [comment]
Hi Ahmed,

Thanks for reporting. 

Unfortunately, I can't think of a way to currently handle this except by first filtering your file and removing quotes. If you want help with that let me know, I can probably come up with some R-code that does this reasonably fast. Or if you are working under linux a script using `sed` for example.

I think this calls for a `quote` option to `laf_open_csv`. I don't think it is that difficult to add. However, I currently are very limited in time, and don't think I will have time to look into this within the next few weeks. 

Jan

**Comment by elgabbas** [comment]
Thanks Jan for your reply,
Could you, please, let me know how to filter such huge file and remove the quotes without loading it to the memory (using R under windows)? 

Ahmed

**Comment by djvanderlaan** [comment]
Ahmed,

You can use something like:

```{r}
# open the input and output files
conin <- file("yourfile.csv", "rt")
conout <- file("out.csv", "wt")
# we will be reading blocks of data: number of lines read:
blocksize <- 1E6
while(TRUE) {
  lines <- readLines(con, n=blocksize)
  # replace '"' by '', using fixed=TRUE is much faster
  lines <- gsub('"', '', lines, fixed=TRUE)
  # write the lines without the '"' to the output connection
  writeLines(lines, conout)
  # test to see if we have reached the end of the file; if so quite loop
  if (length(lines) < blocksize) break;
}
close(conin)
close(conout)
```

**Comment by elgabbas** [comment]
Thanks a lot Jan,

Ahmed
