### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by djvanderlaan** [djvanderlaan/LaF#8]
When opening and closing a large number of CSV files (perhaps also fixed width?) LaF leaks memory. 
Even when closing the file connections.

**Comment by pdbailey0** [comment]
@djvanderlaan do you have any ideas about how to fix this? Could this be related to [this thread](https://stat.ethz.ch/pipermail/r-devel/2016-November/073360.html) on R-devel?

**Comment by pdbailey0** [comment]
Here is an example, if you need one:

run once:
```
library(gdata)
library(LaF)
library(pryr)

# Generate random fwf file
set.seed(42)
df <- data.frame(id = 1:1e6, 
                 number = round(runif(1e6, 0, 100), digits = 3),
                 text = "Example")
write.fwf(df, "file.fwf",
          rownames = FALSE,
          colnames = FALSE)

# This does not change memory
laf_open_fwf(filename="file.fwf",
                        column_types=c("integer", "double", "string"),
                        column_names=c("id", "num", "text"),
                        column_widths = c(7, 7, 7))
```

then, debug with:
```
library(LaF)
library(pryr)
library(gdata)
# Call data inside function does change memory
getDataTemp <- function(){
  data <- laf_open_fwf(filename="file.fwf",
                       column_types=c("integer", "double", "string"),
                       column_names=c("id", "num", "text"),
                       column_widths = c(7, 7, 7))
  alldata <- data[,]
  close(data)
  return(alldata)
}

for(i in 1:5) {
  getDataTemp()
  print(mem_used())
}
```

**Comment by pdbailey0** [comment]
OK, this causes problems (the memory gets gobbled up), but they don't get worse as you read in the data again and again.
```
library(LaF)
library(pryr)
# This does not change memory
ff <- laf_open_fwf(filename="file.fwf",
                   column_types=c("integer", "double", "string"),
                   column_names=c("id", "num", "text"),
                   column_widths = c(7, 7, 7))

getDataTemp <- function(){
  alldata <- ff[,]
  return(alldata)
}

mem_used()
for(i in 1:5) {
  getDataTemp()
  print(mem_used())
}
```
I think it's only because we open new connections. This might make one wonder why we use `LaF`, but I think it can be fixed.

**Comment by djvanderlaan** [comment]
Paul,Thanks for reporting. And also thanks for the example. Tomorrow I have a substantial train trip ahead of me, so I'll probably have some time to look at this. Op 2 okt. 2017 21:47 schreef Paul Bailey <notifications@github.com>:OK, this causes problems (the memory gets gobbled up), but they don't get worse as you read in the data again and again.
library(LaF)
library(pryr)
# This does not change memory
ff <- laf_open_fwf(filename="file.fwf",
                   column_types=c("integer", "double", "string"),
                   column_names=c("id", "num", "text"),
                   column_widths = c(7, 7, 7))

getDataTemp <- function(){
  alldata <- ff[,]
  return(alldata)
}

mem_used()
for(i in 1:5) {
  getDataTemp()
  print(mem_used())
}

I think it's only because we open new connections. This might make one wonder why we use LaF, but I think it can be fixed.

**Comment by pdbailey0** [comment]
Thanks for the update. LaF has been super helpful to us on [EdSurvey](https://CRAN.R-project.org/package=EdSurvey). Thanks for developing it!

**Comment by pdbailey0** [comment]
I was able to confirm that this is also a problem with .csv files

```
library(gdata)
library(LaF)
library(pryr)

# Generate random fwf file
set.seed(42)
df <- data.frame(id = 1:1e6, 
                 number = round(runif(1e6, 0, 100), digits = 3),
                 text = "Example")
write.csv(df, "file.csv")

getDataTemp <- function(){
  data <- laf_open_csv(filename="file.csv",
                       column_types=c("integer", "integer", "double", "string"),
                       column_names=c("X", "id", "num", "text"))
  print(system.time(alldata <- data[2:nrow(data),]))
  print(system.time(alldata2 <- data[2:nrow(data),]))
  print(system.time(alldata3 <- data[2:nrow(data),]))
  close(data)
  return(alldata)
}

for(i in 1:5) {
  getDataTemp()
  print(mem_used())
}
```

it also appears to leak more the more that gets read in. However, reading in the same data multiple times does not increase the amount of memory used.

**Comment by djvanderlaan** [comment]
Sorry for not reporting back earlier. I have had look, but, to be honest, I don't really understand what is happening. The amount leaked is exactly the size of the data read. It looks like the dataset is not cleaned up by the garbage collector of R for some reason. But what I don't understand is, why is there no leak when the connection is opened once and the dataset is read multiple times? 

That the csv reader has the same problem doesn't really surprise me: they share much of the code. I suspect the problem is with the (c++) code that reads a chunk of data and that is reader independent. 

I'll look some more into it next week.

**Comment by djvanderlaan** [comment]
Finally managed to track down the cause. It should be fixed now. 

Will push a new version to CRAN later this week.

**Comment by pdbailey0** [comment]
That's great news! We're testing it with EdSurvey now.

**Comment by pdbailey0** [comment]
From our testing, this fixed all or most of the problem. It looks like you still need to close a connection to release the memory, but I think it has always been the deal that when you open a connection you're responsible for closing it.

Thank you for fixing this!
