### ISSUE TITLE
detect_dm_csv cost too long time for wide data

### ISSUE THREAD

**Issue by earthcli** [djvanderlaan/LaF#9]
I have a wide dataset of more than 10000 columns and 5 rows. when using detect_dm_csv function, it cost too long time, How should I do?

**Comment by djvanderlaan** [comment]
Do you know the types of the columns, e.g. are they alle numeric? In that case you don't need `detect_dm_csv`. You can then use something like:

```{R}
l <- laf_open_csv("filename.csv", column_types = rep("numeric", 1000))
```

Another solution is to decrease the number of lines that is read in by `detect_dm_csv` using the `nrows` argument. By default it reads 1000 lines. If all your fields are filed, you might get away with reading just a few lines.

**Comment by earthcli** [comment]
Thanks for your respond!
In fact, my data have a dynamic column number, which is written in the file(the upper left corner), so if i can only read the first row and first tow column then the column number is known.
while  l <- laf_open_csv("filename.csv", column_types = rep("character", 1000000)) works, but How can I get the real NCOL?

**Comment by djvanderlaan** [comment]
I am sorry it took a while to get back to you. I was away on vacation so had limited access to internet. 

As you have the number of column in the first line of your file, the folling should get you the number of columns:

```{r}
ncol <- readLines("filename.csv", n = 1)
ncol <- as.integer(ncol)
```

And then you can use:

```{r}
 l <- laf_open_csv("filename.csv", column_types = rep("character", ncol))
```
